### ISSUE TITLE
getToken() does not check domain

### ISSUE THREAD

**Issue by 001SPARTaN** [vysec/ANGRYPUPPY#7]
The `getToken` function in ANGRYPUPPY.cna does not check the domain of credentials, giving it a chance of using the wrong credentials if there are two accounts with same username, but different domain.

I'm thinking we may be able to change `bhUserToCS-sub` in utils.cna to return an array with `@($user, $domain)`, but this poses the issue of different domain representations (e.g. LAB.DOMAIN\user vs LAB\user). May have to normalize this before we perform the check.

Thanks to xan7r for discovering this issue.

**Comment by 001SPARTaN** [comment]
Some more stuff to consider after discussion with @vysec this morning.
- We don't have a way to normalize FQDN (from BloodHound), and NETBIOS domain name (from Mimikatz)
- We considered adding a realm option in the initial dialog, but that presents issues when we want to traverse realms

**Comment by 001SPARTaN** [comment]
UPDATE:

We have implemented basic checks to see if the first portion of the FQDN matches the NETBIOS domain name. This isn't a perfect solution to the problem, but seems to be the best we can do, given that there isn't always a direct relationship between the two.

**Comment by vysec** [comment]
We could do this in future by querying in mimikatz and sending a NETBIOS name to FQDN map then make the script figure it out. But this will require command output capture and parsing.
